# Workflow state mappings for different workflow types
workflow_states:
  workflow_transfer_payment:
    0: "stInit"
    100: "stTransferPersisted"
    101: "stProcessingPublished"
    102: "stTransactionLimitChecked"
    103: "stRedeemRewardRequired"
    104: "stResolveFeeRequired"
    105: "stFreeTransferFeeRewardRedeemed"
    106: "stFeeResolved"
    210: "stAuthProcessing"
    211: "stAuthStreamPersisted"
    220: "stTransferProcessing"
    221: "stTransferStreamPersisted"
    223: "stTransferCompleted"
    230: "stCaptureProcessing"
    231: "stCaptureStreamPersisted"
    235: "stCapturePrepared"
    300: "stAuthCompleted"
    400: "stTransferFailed"
    410: "stAutoCancelProcessing"
    412: "stAutoCancelStreamPersisted"
    501: "stPrepareFailureHandling"
    505: "stFailurePublished"
    510: "stFailureNotified"
    511: "stRewardRedeemVoidRequired"
    512: "stRewardRedeemVoided"
    701: "stCaptureFailed"
    702: "stCancelFailed"
    703: "stRewardRedeemInterventionRequired"
    900: "stCaptureCompleted"
    905: "stCompletedPublished"
    910: "stCompletedNotified"
    911: "stRewardRedeemCompletionRequired"
    912: "stRewardRedeemCompleted"

  internal_payment_flow:
    0: "stInit"
    100: "stPending"
    101: "stStreamPersisted"
    500: "stFailed"
    501: "stPrepareFailurePublish"
    900: "stSuccess"
    901: "stPrepareUpdateAuth"
    902: "stPrepareSuccessPublish"

  external_payment_flow:
    0: "stInit"
    200: "stSubmitted"
    201: "stProcessing"
    202: "stRespReceived"
    500: "stFailed"
    501: "stPrepareFailurePublish"
    900: "stPrepareSuccessPublish"
    901: "stSuccess"

  wf_ct_cashin:
    0: "stInit"
    100: "stTransferPersisted"
    110: "stRequestToPayUpdated"
    111: "stRequestToPayUpdateFailed"
    121: "stOriginalTransferValidated"
    122: "stFieldsValidationFailed"
    200: "stTransferProcessing"
    201: "stTransferStreamPersisted"
    210: "stTransferUpdated"
    220: "stTransferRespPrepared"
    700: "stCashInFailed"
    701: "stCashInToRefund"
    900: "stCashInCompleted"
    901: "stCashInCompletedWithRefund"

  wf_ct_cashout:
    0: "stInit"
    101: "stCreditTransferPersisted"
    111: "stCreditorDetailUpdated"
    120: "stPrepareCreditorInquiry"
    121: "stCreditorInquiryFailed"
    122: "stCreditorInquirySuccess"
    210: "stTransferProcessing"
    211: "stTransferResponseReceived"
    212: "stTransferMessageRejectedReceived"
    221: "stTransferManualRejectedReceived"
    222: "stTransferManualResumeReceived"
    301: "stPrepareSuccessPublish"
    311: "stPrepareFailurePublish"
    321: "stSkipPublish"
    502: "stTransferRetryAttemptExceeded"
    700: "stFailed"
    900: "stSuccess"

  wf_ct_qr_payment:
    0: "stInit"
    101: "stCreditTransferPersisted"
    111: "stCreditorDetailUpdated"
    120: "stPrepareCreditorInquiry"
    121: "stCreditorInquiryFailed"
    122: "stCreditorInquirySuccess"
    210: "stTransferProcessing"
    211: "stTransferResponseReceived"
    212: "stTransferMessageRejectedReceived"
    221: "stTransferManualRejectedReceived"
    222: "stTransferManualResumeReceived"
    301: "stPrepareSuccessPublish"
    311: "stPrepareFailurePublish"
    321: "stSkipPublish"
    502: "stTransferRetryAttemptExceeded"
    700: "stFailed"
    900: "stSuccess"

  wf_ct_rtp_cashin:
    0: "stInit"
    100: "stTransferPersisted"
    110: "stRequestToPayUpdated"
    111: "stRequestToPayUpdateFailed"
    121: "stOriginalTransferValidated"
    122: "stFieldsValidationFailed"
    200: "stTransferProcessing"
    201: "stTransferStreamPersisted"
    210: "stTransferUpdated"
    220: "stTransferRespPrepared"
    700: "stCashInFailed"
    701: "stCashInToRefund"
    900: "stCashInCompleted"
    901: "stCashInCompletedWithRefund"

  workflow_charge:
    0: "stInit"
    100: "stProcessingPublished"
    101: "stPrepareAuth"
    102: "stPrepareTransfer"
    200: "stAuthProcessing"
    201: "stTriggerInAppAuth"
    210: "stTransferProcessing"
    300: "stAuthCompleted"
    301: "stPendingInAppAuth"
    302: "stInAppAuthStreamPersisted"
    310: "stPublishAuth"
    400: "stCaptureProcessing"
    500: "stCaptureFailed"
    501: "stCancelFailed"
    502: "stFailureNotified"
    600: "stCancelProcessing"
    700: "stCancelCompleted"
    777: "stCancelPublished"
    800: "stTransferCompleted"
    871: "stTransferPublishedDirectNotify"
    888: "stTransferPublished"
    890: "stNotified"
    900: "stPrepareFailureHandling"
    999: "stFailurePublished"

  workflow_transfer_collection:
    0: "stInit"
    100: "stTransferPersisted"
    101: "stProcessingPublished"
    102: "stPreTransactionLimitCheck"
    103: "stPreRiskCheck"
    210: "stTransferProcessing"
    211: "stTransferStreamPersisted"
    220: "stAuthProcessing"
    221: "stAuthStreamPersisted"
    230: "stCapturePrepared"
    231: "stCaptureProcessing"
    232: "stCaptureStreamPersisted"
    240: "stCancelPrepared"
    241: "stCancelProcessing"
    242: "stCancelStreamPersisted"
    250: "stResumePrepared"
    300: "stAuthSuccess"
    501: "stPrepareFailureHandling"
    502: "stTransactionLimitCheckFailed"
    503: "stRiskCheckError"
    504: "stRiskCheckDeny"
    505: "stFailurePublished"
    510: "stFailureNotified"
    600: "stCanceled"
    610: "stCanceledPublished"
    701: "stCaptureFailed"
    702: "stCancelFailed"
    721: "stInvestigationRequiredPublished"
    722: "stInvestigationRequiredNotified"
    800: "stValidateSuccess"
    900: "stTransferCompleted"
    901: "stCaptureCompleted"
    902: "stTransferCompletedAutoPublish"
    905: "stCompletedPublished"
    910: "stCompletedNotified"

  wf_process_registry:
    0: "stInit"
    100: "stRppMsgPersisted"
    201: "stRppMsgVerified"
    202: "stRppMsgVerifyFailed"
    700: "stFailed"
    900: "stSuccess"
