# Fast adapter state mappings for different adapter types
fast_adapter_states:
  cashout:
    1: "StPending"
    2: "StErraneous"
    3: "StAccepted"
    4: "StRejected"

  cashin:
    1: "StAuthed"
    2: "StAuthUnknown"
    3: "StConfirmUnknown"
    4: "StCancelUnknown"
    5: "StErraneous"
    6: "StConfirmed"
    7: "StCanceled"
    8: "StCanceledManual"
    9: "StRejected"
    11: "StReversed"
    12: "StReversedUnknown"
    13: "StReversedManual"
    15: "StCancelAcknowledged"
    17: "StAuthedNoStatus"
    18: "StRejectedNoStatus"
